language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install: pip install -r requirements.txt --use-mirrors
before_script: python setup.py pep8
script: exit 0

notifications:
  email:
    - farscape-dev@lists.rackspace.com
