language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install: pip install -r requirements.txt --use-mirrors
script: ./scripts/verify_code_bundle.sh && python setup.py pep8

notifications:
  email:
    - farscape-build-notifications@lists.rackspace.com
